### ISSUE TITLE
Doesn't work with Two-Factor Auth turned on

### ISSUE THREAD

**Issue by StoppingBuck** [rubyconn/steam-chat#1]
Hi,

As far as I can see, steam-chat doesn't seem to work if your Steam Account has Two-Factor Authentication turned on. When trying to log-in with correct username and password, the client returns the following:

`11:31 - Steam: Successfully connected to servers.     │`
`11:31 - Steam: AccountLogonDeniedNeedTwoFactorCode    │`
`11:31 - Steam: AccountLoginDeniedNeedTwoFactor        │`
`11:31 - Steam: Error: Disconnected                    │`

**Comment by rubyconn** [comment]
I've added `/set twofactor VALUE` which you could try to use. Two-factor auth has been implemented but never tested as I haven't enabled it on my account.

**Comment by StoppingBuck** [comment]
That indeed seems to do the trick! I can log-in with two-factor auth perfectly now :) . Perhaps this should be mentioned in the documentation somewhere?

**Comment by rubyconn** [comment]
That's good to hear. There's probably a lack of documentation for this repo. I've added an error message mentioning the command if your account has two-factor enabled to the new branch, and I'll be sure to write some login documentation later. 60cda1dd4866e997a97814332efec34172aed9cc
