### ISSUE TITLE
Cannot retrieve server list/functional servers

### ISSUE THREAD

**Issue by somehibs** [rubyconn/steam-chat#6]
Hey uosl,

Thanks for the excellent terminal client. I've been enjoying intermittent use of it when I'm away from a computer I'm comfortable using Steam on.

I called `npm start` today and discovered that I cannot proceed past `Connecting to the Steam servers`.
I've tried removing servers.json and config.json, but to no effect.

Got any tips on diagnosing this issue?
Thanks for your time.

**Comment by uosl** [comment]
Hello,

Thanks for creating this issue. Development has become kind of stale, but I try to keep it working for simple chat stuff.

I remember reading that Steam has reworked their API or something, as well as an issue on github.com/seishun/node-steam about difficulty connecting to Steam servers. I'm not sure if I have to just change the server connection code, or if the entire Steam library needs to be updated?

I'm currently in a mountain cabin with barely any mobile signal, and no computers, so I'll look into it more thoroughly next week when I'm home. Sorry that I can't be more helpful than this right now.




On 14 August 2018 15:59:27 CEST, somehibs <notifications@github.com> wrote:
>Hey uosl,
>
>Thanks for the excellent terminal client. I've been enjoying
>intermittent use of it when I'm away from a computer I'm comfortable
>using Steam on.
>
>I called `npm start` today and discovered that I cannot proceed past
>`Connecting to the Steam servers`.
>I've tried removing servers.json and config.json, but to no effect.
>
>Got any tips on diagnosing this issue?
>Thanks for your time.

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
